name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  camera_web: ^0.3.2+4
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  empty_widget: ^0.0.5
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  loader_overlay: ^4.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
